// ============================================================
//  DEALGOD – AMAZON ASSOCIATES PRODUCT DATA
//  Edit products below. Replace YOUR_AFFILIATE_TAG with yours.
//  Image URLs use Amazon's official CDN — all publicly accessible.
// ============================================================

const SITE_CONFIG = {
  siteName: "DealGod",
  tagline: "The God of Amazon Deals.",
  affiliateTag: "dealgodteam-21", // <-- Replace with your Amazon Associate tag
  siteUrl: "https://dealgod.netlify.app",
  launchMode: "production",
  features: {
    enableFomoPopups: false,      // keep false for production trust
    enablePushPromptMock: false,  // keep false for production
  },
  // Optional analytics (leave disabled if you don't want tracking)
  // provider: "plausible" with your domain, OR provider: "ga4" with measurementId
  analytics: {
    provider: "ga4", // "plausible" | "ga4"
    domain: "", // plausible domain, e.g. "dealgod.netlify.app"
    measurementId: "G-YV1DGYW3Y0" // GA4 measurement id, e.g. "G-XXXXXXXXXX"
  }
};

// Deal end times (optional - add "dealEnds" to any product for countdown timer)
// Format: ISO date string e.g. "2026-04-28T23:59:59"
// Remove or set to null to disable countdown for a product

const CATEGORIES = [
  "All",
  "Electronics",
  "Home & Kitchen",
  "Books",
  "Fashion",
  "Health & Beauty",
  "Sports & Fitness",
  "Gaming",
  "Smart Home",
  "Toys & Games",
  "Office & Stationery",
  "Appliances",
  "Automotive",
  "Baby & Kids",
  "Musical Instruments"
];

const PRODUCTS = [
  // NOTE: window exposure happens at end of file
  // ---- ELECTRONICS ----
  {
    id: 1,
    title: "Apple AirPods Pro (2nd Gen) – USB-C",
    description:
      "Active Noise Cancellation, Adaptive Audio, Transparency mode. 30-hour total battery life with case.",
    price: "₹24,900",
    originalPrice: "₹26,900",
    discount: "7%",
    category: "Electronics",
    rating: 4.5,
    reviews: 5421,
    image: "https://m.media-amazon.com/images/I/71bhWgQK-cL._AC_SL1500_.jpg",
    asin: "B0CHX1W1XY",
    badge: "Best Seller",
    bankOffer: "Flat ₹2,000 off on HDFC Cards",
    priceHistory: "Lowest price in 30 days",
    dealScore: 98,
    couponCode: "HDFC2000"
  },
  {
    id: 2,
    title: "boAt Airdopes 141 Gen 2 TWS Earbuds",
    description:
      "48hr total playback, 4 Mics ENx Tech for clear calls, Beast Mode gaming, IPX4 water resistant.",
    price: "₹899",
    originalPrice: "₹2,990",
    discount: "70%",
    category: "Electronics",
    rating: 3.8,
    reviews: 89423,
    image: "https://m.media-amazon.com/images/I/61sHD9HC-cL._AC_SL1500_.jpg",
    asin: "B0F8BVSK21",
    badge: "Deal of the Day",
    dealScore: 85,
  },
  {
    id: 3,
    title: "Amazon Fire TV Stick 4K (2024)",
    description:
      "Wi-Fi 6 support, Dolby Vision & Atmos, Alexa Voice Remote with TV controls. Stream 4K content.",
    price: "₹4,299",
    originalPrice: "₹6,999",
    discount: "39%",
    category: "Electronics",
    rating: 3.8,
    reviews: 34210,
    image: "https://m.media-amazon.com/images/I/61ewZTejmaL._AC_SL1500_.jpg",
    asin: "B0CN3ZGJ6H",
    badge: "Amazon Pick",
  },
  {
    id: 4,
    title: "All-New Kindle Paperwhite (16GB) – 7\" Display",
    description:
      "7-inch glare-free display, adjustable warm light, 12 weeks battery, waterproof IPX8. Thinnest Kindle ever.",
    price: "₹16,999",
    originalPrice: "₹21,999",
    discount: "23%",
    category: "Electronics",
    rating: 4.5,
    reviews: 18920,
    image: "https://m.media-amazon.com/images/I/61Wbqg0N4mL._AC_SL1500_.jpg",
    asin: "B0DKTZ6592",
    badge: "Top Pick",
    couponCode: "SAVE500"
  },
  {
    id: 5,
    title: "boAt Rockerz 550 Bluetooth Headphone",
    description:
      "50mm drivers, 20-hour battery, foldable ear-cups, immersive surround sound. Premium build.",
    price: "₹1,299",
    originalPrice: "₹3,990",
    discount: "67%",
    category: "Electronics",
    rating: 4.3,
    reviews: 15892,
    image: "https://m.media-amazon.com/images/I/71ggxv5CjOL._AC_SL1500_.jpg",
    asin: "B084NS1JGK",
    badge: "Great Value",
  },
  {
    id: 6,
    title: "Amazon Echo Dot 5th Gen (2023)",
    description:
      "Compact smart speaker with Alexa. Improved bass, motion detection, temperature sensor & smart home hub.",
    price: "₹3,499",
    originalPrice: "₹5,499",
    discount: "36%",
    category: "Electronics",
    rating: 4.4,
    reviews: 11230,
    image: "https://m.media-amazon.com/images/I/71xoR4A6q3L._AC_SL1500_.jpg",
    asin: "B09B8RVKGW",
    badge: "Trending",
  },
  {
    id: 7,
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    description:
      "Industry-leading noise cancellation, 30-hour battery, crystal clear hands-free calling, multipoint connect.",
    price: "₹24,990",
    originalPrice: "₹34,990",
    discount: "29%",
    category: "Electronics",
    rating: 4.5,
    reviews: 7312,
    image: "https://m.media-amazon.com/images/I/61HE3T5TFXL._AC_SL1500_.jpg",
    asin: "B09XS7JWHH",
    badge: "Editor's Choice",
    dealScore: 95,
  },
  {
    id: 8,
    title: "Redmi 13C 5G (6GB + 128GB)",
    description:
      "Dimensity 6100+ chipset, 50MP AI camera, 5000mAh battery, 90Hz display. Best budget 5G phone.",
    price: "₹10,999",
    originalPrice: "₹13,999",
    discount: "21%",
    category: "Electronics",
    rating: 4.2,
    reviews: 43521,
    image: "https://m.media-amazon.com/images/I/81CxC3VVPGL._AC_SL1500_.jpg",
    asin: "B0CNX7BZ7R",
    badge: "Bestseller",
    bankOffer: "10% off with SBI Credit Cards",
    priceHistory: "Usually ₹12,999",
    dealScore: 92,
  },

  // ---- HOME & KITCHEN ----
  {
    id: 9,
    title: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
    description:
      "Pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker & warmer. 5.7L.",
    price: "₹7,499",
    originalPrice: "₹11,995",
    discount: "37%",
    category: "Home & Kitchen",
    rating: 4.7,
    reviews: 8921,
    image: "https://m.media-amazon.com/images/I/71V1chNMGkL._AC_SL1500_.jpg",
    asin: "B00FLYWNYQ",
    badge: "Top Pick",
    dealScore: 95,
  },
  {
    id: 10,
    title: "Pigeon Healthifry Digital Air Fryer – 4.2L",
    description:
      "1200W, 8 preset modes, 360° rapid heat circulation for oil-free frying, baking and grilling.",
    price: "₹2,799",
    originalPrice: "₹6,499",
    discount: "57%",
    category: "Home & Kitchen",
    rating: 4.3,
    reviews: 7102,
    image: "https://m.media-amazon.com/images/I/81WUVn3LKJL._AC_SL1500_.jpg",
    asin: "B09NVQK62Y",
    badge: "New Arrival",
  },
  {
    id: 11,
    title: "Milton Thermosteel Flip Lid Flask 1000ml",
    description:
      "Hot & cold for 24 hours, food-grade 304 stainless steel, leak-proof flip lid, BPA-free.",
    price: "₹549",
    originalPrice: "₹1,095",
    discount: "50%",
    category: "Home & Kitchen",
    rating: 4.4,
    reviews: 31290,
    image: "https://m.media-amazon.com/images/I/71xBfGmSJNL._AC_SL1500_.jpg",
    asin: "B01MXIUGBY",
    badge: "Bestseller",
  },
  {
    id: 12,
    title: "Prestige Iris 750W Mixer Grinder (3 Jars)",
    description:
      "750W motor, 3 stainless steel jars, speed control, coupler system. 5-year warranty on motor.",
    price: "₹2,199",
    originalPrice: "₹4,500",
    discount: "51%",
    category: "Home & Kitchen",
    rating: 4.3,
    reviews: 19430,
    image: "https://m.media-amazon.com/images/I/71AxBuH5iqL._AC_SL1500_.jpg",
    asin: "B07B7FBKM6",
    badge: "Great Value",
  },
  {
    id: 13,
    title: "Syska 9W LED Bulb Pack of 10",
    description:
      "9W LED, 900 lumens, cool white, B22 base. Energy saving – replaces 75W incandescent bulbs.",
    price: "₹349",
    originalPrice: "₹850",
    discount: "59%",
    category: "Home & Kitchen",
    rating: 4.2,
    reviews: 22810,
    image: "https://m.media-amazon.com/images/I/51FuBPdKJ7L._AC_SL1500_.jpg",
    asin: "B07CG8YWMZ",
    badge: "",
  },

  // ---- BOOKS ----
  {
    id: 14,
    title: "Atomic Habits – James Clear",
    description:
      "The life-changing #1 bestseller. Tiny Changes, Remarkable Results. Build good habits and break bad ones.",
    price: "₹399",
    originalPrice: "₹799",
    discount: "50%",
    category: "Books",
    rating: 4.9,
    reviews: 21453,
    image: "https://m.media-amazon.com/images/I/81wgcld4wxL._AC_SY466_.jpg",
    asin: "B01N5AX61W",
    badge: "Editor's Choice",
    dealScore: 99,
  },
  {
    id: 15,
    title: "Rich Dad Poor Dad – Robert Kiyosaki",
    description:
      "What the rich teach their kids about money that the poor and middle class do not. All-time bestseller.",
    price: "₹285",
    originalPrice: "₹350",
    discount: "18%",
    category: "Books",
    rating: 4.7,
    reviews: 33210,
    image: "https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_SY466_.jpg",
    asin: "1612680194",
    badge: "Bestseller",
  },
  {
    id: 16,
    title: "The Psychology of Money – Morgan Housel",
    description:
      "18 short stories exploring strange ways people think about money. Essential reading for financial clarity.",
    price: "₹349",
    originalPrice: "₹499",
    discount: "30%",
    category: "Books",
    rating: 4.8,
    reviews: 17821,
    image: "https://m.media-amazon.com/images/I/71g2ednj0JL._AC_SY466_.jpg",
    asin: "B08D9WJ9G8",
    badge: "Top Pick",
  },
  {
    id: 17,
    title: "The Alchemist – Paulo Coelho",
    description:
      "A world-renowned novel about following your dreams and listening to your heart. Over 65 million copies sold.",
    price: "₹199",
    originalPrice: "₹399",
    discount: "50%",
    category: "Books",
    rating: 4.7,
    reviews: 28910,
    image: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_SY466_.jpg",
    asin: "0062315005",
    badge: "Popular",
  },

  // ---- FASHION ----
  {
    id: 18,
    title: "Nike Air Max 270 Running Shoes",
    description:
      "Large Max Air heel unit for all-day comfort, breathable mesh upper. Multiple colours and sizes.",
    price: "₹7,497",
    originalPrice: "₹11,995",
    discount: "37%",
    category: "Fashion",
    rating: 4.6,
    reviews: 3411,
    image: "https://m.media-amazon.com/images/I/71W+-C3A7XL._AC_UX695_.jpg",
    asin: "B082FPYQCM",
    badge: "Trending",
    bankOffer: "Extra 5% off on ICICI",
    dealScore: 88,
  },
  {
    id: 19,
    title: "Levi's 511 Slim Fit Stretchable Jeans",
    description:
      "Premium 97% cotton, slim-fit taper below knee. Available in dark and light wash. Classic style.",
    price: "₹1,799",
    originalPrice: "₹3,999",
    discount: "55%",
    category: "Fashion",
    rating: 4.3,
    reviews: 14320,
    image: "https://m.media-amazon.com/images/I/71u5eDHUSML._AC_UY879_.jpg",
    asin: "B09C9FXJT9",
    badge: "Great Value",
  },
  {
    id: 20,
    title: "Puma Men's Running Shoes",
    description:
      "Lightweight EVA cushioning, synthetic mesh upper, anti-slip rubber outsole. Breathable and flexible.",
    price: "₹2,099",
    originalPrice: "₹5,999",
    discount: "65%",
    category: "Fashion",
    rating: 4.3,
    reviews: 8921,
    image: "https://m.media-amazon.com/images/I/71cKFqXnDKL._AC_UX695_.jpg",
    asin: "B07XLBSF8P",
    badge: "Deal of the Day",
    dealEnds: "2026-04-27T23:59:59",
  },
  {
    id: 21,
    title: "Tommy Hilfiger Analog Wrist Watch",
    description:
      "Stainless steel case, leather strap, water resistant 50m. Elegant design for formal and casual wear.",
    price: "₹4,795",
    originalPrice: "₹9,995",
    discount: "52%",
    category: "Fashion",
    rating: 4.5,
    reviews: 6712,
    image: "https://m.media-amazon.com/images/I/71k6BqJ9HaL._AC_UY879_.jpg",
    asin: "B0055SLZVU",
    badge: "Editor's Choice",
  },

  // ---- HEALTH & BEAUTY ----
  {
    id: 22,
    title: "Philips BHD501 Hair Dryer with Diffuser",
    description:
      "1200W, ThermoProtect, ionized airflow for frizz control, cool shot button. Lightweight design.",
    price: "₹1,695",
    originalPrice: "₹2,995",
    discount: "43%",
    category: "Health & Beauty",
    rating: 4.4,
    reviews: 9823,
    image: "https://m.media-amazon.com/images/I/61yNbFxkl4L._AC_SL1500_.jpg",
    asin: "B07B43DHPK",
    badge: "",
  },
  {
    id: 23,
    title: "Mamaearth Ubtan Foaming Face Wash",
    description:
      "Natural brightening with turmeric and saffron. Removes dead cells, reduces dark spots. 150ml.",
    price: "₹199",
    originalPrice: "₹299",
    discount: "33%",
    category: "Health & Beauty",
    rating: 4.4,
    reviews: 11203,
    image: "https://m.media-amazon.com/images/I/61cBHQrp0hL._AC_SL1500_.jpg",
    asin: "B07QJLQXD9",
    badge: "",
  },
  {
    id: 24,
    title: "MuscleBlaze Whey Gold Protein 1kg",
    description:
      "25g protein per serving, 5.5g BCAAs, Labdoor USA certified. Rich chocolate flavour.",
    price: "₹1,699",
    originalPrice: "₹2,899",
    discount: "41%",
    category: "Health & Beauty",
    rating: 4.5,
    reviews: 24310,
    image: "https://m.media-amazon.com/images/I/71qwq72sWbL._AC_SL1500_.jpg",
    asin: "B085RHTB3T",
    badge: "Best Seller",
    dealEnds: "2026-04-30T23:59:59",
    priceHistory: "Lowest price ever",
    dealScore: 94,
  },
  {
    id: 25,
    title: "Beardo Beard & Hair Growth Oil 50ml",
    description:
      "Enriched with 10 natural oils — boosts growth, reduces patchy beard, nourishes skin beneath.",
    price: "₹249",
    originalPrice: "₹399",
    discount: "37%",
    category: "Health & Beauty",
    rating: 4.2,
    reviews: 8432,
    image: "https://m.media-amazon.com/images/I/61BRNlBifBL._AC_SL1500_.jpg",
    asin: "B07J5BFHB6",
    badge: "",
  },

  // ---- SPORTS & FITNESS ----
  {
    id: 26,
    title: "Boldfit Resistance Bands Set (Pack of 5)",
    description:
      "5-level resistance loop bands for home workout, yoga, stretching. Non-slip fabric, washable.",
    price: "₹499",
    originalPrice: "₹1,299",
    discount: "61%",
    category: "Sports & Fitness",
    rating: 4.2,
    reviews: 6754,
    image: "https://m.media-amazon.com/images/I/81kBpYqMBDL._AC_SL1500_.jpg",
    asin: "B08FT4K3BR",
    badge: "Popular",
  },
  {
    id: 27,
    title: "Strauss Anti-Skid EVA Yoga Mat 6mm",
    description:
      "Extra thick 6mm dual-layer foam, double-sided anti-skid texture. Includes carry strap. 183cm x 61cm.",
    price: "₹599",
    originalPrice: "₹1,499",
    discount: "60%",
    category: "Sports & Fitness",
    rating: 4.3,
    reviews: 18321,
    image: "https://m.media-amazon.com/images/I/81nOtUSBfML._AC_SL1500_.jpg",
    asin: "B07BSHV96N",
    badge: "Great Value",
  },
  {
    id: 28,
    title: "Fitkit FK500 Fitness Band",
    description:
      "Heart rate & SpO2 monitor, 10 sports modes, 7-day battery, IP68 waterproof, sleep tracker.",
    price: "₹999",
    originalPrice: "₹2,999",
    discount: "67%",
    category: "Sports & Fitness",
    rating: 4.1,
    reviews: 9821,
    image: "https://m.media-amazon.com/images/I/61IrNya3h3L._AC_SL1500_.jpg",
    asin: "B0BHFR2C5Y",
    badge: "New Arrival",
  },
  {
    id: 29,
    title: "Yonex ZR 100 Light Badminton Set",
    description:
      "2 aluminium rackets + 3 shuttlecocks + carry bag. Ideal for beginners and recreational play.",
    price: "₹749",
    originalPrice: "₹1,499",
    discount: "50%",
    category: "Sports & Fitness",
    rating: 4.1,
    reviews: 5430,
    image: "https://m.media-amazon.com/images/I/81qz7OElFIL._AC_SL1500_.jpg",
    asin: "B07MHXJRZQ",
    badge: "",
  },
  {
    id: 30,
    title: "Cockatoo CFD05 Adjustable Dumbbell Set 10kg",
    description:
      "5 pair dumbbell set (1kg–5kg), textured grip handles, chrome plated. Ideal home gym starter kit.",
    price: "₹899",
    originalPrice: "₹2,499",
    discount: "64%",
    category: "Sports & Fitness",
    rating: 4.3,
    reviews: 12301,
    image: "https://m.media-amazon.com/images/I/71JKS4LLKBL._AC_SL1500_.jpg",
    asin: "B08CTHBGMK",
    badge: "Best Seller",
  },
  {
    id: 31,
    title: "Sony PlayStation 5 Console",
    description: "Lightning fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback, and 3D Audio.",
    price: "₹49,990",
    originalPrice: "₹54,990",
    discount: "9%",
    category: "Gaming",
    rating: 4.9,
    reviews: 14500,
    image: "https://m.media-amazon.com/images/I/51mWHXY8hyL._AC_SL1000_.jpg",
    asin: "B0BRCPXGWD",
    badge: "Top Pick",
    bankOffer: "Flat ₹3,000 off on ICICI Cards",
    dealScore: 99,
    couponCode: "GAMEON"
  },
  {
    id: 32,
    title: "Logitech G502 Hero Wired Gaming Mouse",
    description: "High performance Hero 25K Sensor, 11 programmable buttons, adjustable weights, LIGHTSYNC RGB.",
    price: "₹3,995",
    originalPrice: "₹5,495",
    discount: "27%",
    category: "Gaming",
    rating: 4.6,
    reviews: 28900,
    image: "https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_SL1500_.jpg",
    asin: "B07GBZ4Q68",
    badge: "Best Seller"
  },
  {
    id: 33,
    title: "Razer BlackShark V2 X Wired Gaming Headset",
    description: "7.1 Surround Sound, 50mm Drivers, Noise Cancelling Mic, PC, PS4, PS5, Switch, Xbox One, Xbox Series X & S, Mobile.",
    price: "₹3,499",
    originalPrice: "₹5,999",
    discount: "42%",
    category: "Gaming",
    rating: 4.4,
    reviews: 12400,
    image: "https://m.media-amazon.com/images/I/611Z7wFqFHL._AC_SL1500_.jpg",
    asin: "B089SSFSZM",
    badge: "",
    priceHistory: "Lowest price in 60 days"
  },
  {
    id: 34,
    title: "Wipro 12W LED Smart Color Bulb",
    description: "Wi-Fi enabled, 16 million colors, works with Alexa and Google Assistant. Schedule and automate lighting.",
    price: "₹699",
    originalPrice: "₹2,599",
    discount: "73%",
    category: "Smart Home",
    rating: 4.2,
    reviews: 42100,
    image: "https://m.media-amazon.com/images/I/61R-aVwQ3kL._AC_SL1000_.jpg",
    asin: "B07XJ4P81W",
    badge: "Deal of the Day",
    dealEnds: "2026-04-28T23:59:59",
    dealScore: 92,
    couponCode: "SMARTHOME10"
  },
  {
    id: 35,
    title: "Echo Dot (4th Gen, Black) Combo with Wipro 9W Smart Bulb",
    description: "Smart speaker with Alexa and smart bulb combo. Voice control your music, lights, and more.",
    price: "₹3,599",
    originalPrice: "₹6,598",
    discount: "45%",
    category: "Smart Home",
    rating: 4.4,
    reviews: 58000,
    image: "https://m.media-amazon.com/images/I/61N-lZItH8L._AC_SL1000_.jpg",
    asin: "B08VDPW75P",
    badge: "Bundle Deal",
    bankOffer: "10% Instant Discount on SBI Cards"
  },
  {
    id: 36,
    title: "Tapo TP-Link C200 Smart Security Camera",
    description: "360° Pan/Tilt, 1080p Video, Night Vision, Motion Detection, 2-Way Audio, works with Alexa/Google Assistant.",
    price: "₹1,499",
    originalPrice: "₹3,299",
    discount: "55%",
    category: "Smart Home",
    rating: 4.5,
    reviews: 35600,
    image: "https://m.media-amazon.com/images/I/51E1w393FkL._AC_SL1000_.jpg",
    asin: "B07XLML2YS",
    badge: "Amazon Pick"
  },
  {
    id: 37,
    title: "LEGO Technic Monster Jam Megalodon",
    description: "2-in-1 pull-back truck toy rebuilds into a low racer. Great building toy for kids aged 7+.",
    price: "₹1,599",
    originalPrice: "₹1,999",
    discount: "20%",
    category: "Toys & Games",
    rating: 4.8,
    reviews: 12400,
    image: "https://m.media-amazon.com/images/I/81p1Yy4G1HL._AC_SL1500_.jpg",
    asin: "B09BNX3W4D",
    badge: "Amazon Pick"
  },
  {
    id: 38,
    title: "UNO Card Game",
    description: "The classic family card game of matching colors and numbers. Easy to pick up, impossible to put down.",
    price: "₹149",
    originalPrice: "₹299",
    discount: "50%",
    category: "Toys & Games",
    rating: 4.7,
    reviews: 105000,
    image: "https://m.media-amazon.com/images/I/81xH1H7mheL._AC_SL1500_.jpg",
    asin: "B00004TZY8",
    badge: "Best Seller"
  },
  {
    id: 39,
    title: "Hasbro Gaming Monopoly Board Game",
    description: "Classic fast-dealing property trading board game for families and kids aged 8 and up.",
    price: "₹899",
    originalPrice: "₹1,499",
    discount: "40%",
    category: "Toys & Games",
    rating: 4.6,
    reviews: 32000,
    image: "https://m.media-amazon.com/images/I/81tNQeGtyxL._AC_SL1500_.jpg",
    asin: "B07PBW29L1",
    badge: ""
  },
  {
    id: 40,
    title: "Hot Wheels 5-Car Pack",
    description: "5 random highly detailed 1:64 scale die-cast toy cars. A great gift for kids and collectors.",
    price: "₹699",
    originalPrice: "₹749",
    discount: "7%",
    category: "Toys & Games",
    rating: 4.8,
    reviews: 45000,
    image: "https://m.media-amazon.com/images/I/81U2fUUShEL._AC_SL1500_.jpg",
    asin: "B0007R41D8",
    badge: "Top Pick"
  },
  {
    id: 41,
    title: "Casio MJ-12D 12-Digit Desktop Calculator",
    description: "150 steps check and correct, regular percentage, and grand total keys. Dual power (solar + battery).",
    price: "₹450",
    originalPrice: "₹595",
    discount: "24%",
    category: "Office & Stationery",
    rating: 4.5,
    reviews: 75000,
    image: "https://m.media-amazon.com/images/I/71R2oE-B3bL._AC_SL1500_.jpg",
    asin: "B00DPOJ6J2",
    badge: "Best Seller"
  },
  {
    id: 42,
    title: "Parker Vector Matte Black Fountain Pen",
    description: "Smooth writing fountain pen with fine nib, matte black finish with silver trim.",
    price: "₹425",
    originalPrice: "₹500",
    discount: "15%",
    category: "Office & Stationery",
    rating: 4.2,
    reviews: 12000,
    image: "https://m.media-amazon.com/images/I/61Yh-bX06fL._AC_SL1500_.jpg",
    asin: "B00LM3VUKW",
    badge: "Great Value",
    couponCode: "PEN10"
  },
  {
    id: 43,
    title: "BILT Matrix Premium Notebook (Pack of 3)",
    description: "A5 size, single ruled, 160 pages. Premium quality white paper for smooth writing.",
    price: "₹399",
    originalPrice: "₹450",
    discount: "11%",
    category: "Office & Stationery",
    rating: 4.4,
    reviews: 5800,
    image: "https://m.media-amazon.com/images/I/71s8L5A2D2L._AC_SL1500_.jpg",
    asin: "B07Q5W5GDF",
    badge: ""
  },
  {
    id: 44,
    title: "HP Deskjet 2331 Colour Printer",
    description: "Print, copy, scan. USB connectivity. Ideal for home and small office use.",
    price: "₹3,799",
    originalPrice: "₹4,999",
    discount: "24%",
    category: "Office & Stationery",
    rating: 3.9,
    reviews: 28000,
    image: "https://m.media-amazon.com/images/I/61I2qV7J61L._AC_SL1500_.jpg",
    asin: "B08D9NDZ1Y",
    badge: "Deal of the Day",
    bankOffer: "Flat ₹500 off on HDFC Cards"
  },
  {
    id: 45,
    title: "Dyson V8 Absolute Cord-Free Vacuum",
    description: "Powerful suction, up to 40 mins runtime, multiple attachments for deep cleaning.",
    price: "₹29,900",
    originalPrice: "₹43,900",
    discount: "32%",
    category: "Home & Kitchen",
    rating: 4.6,
    reviews: 8900,
    image: "https://m.media-amazon.com/images/I/61-v8jX3aJL._AC_SL1500_.jpg",
    asin: "B0B88K7KXV",
    badge: "Top Pick",
    couponCode: "CLEAN1000"
  },
  {
    id: 46,
    title: "OnePlus 12R (16GB RAM, 256GB)",
    description: "Snapdragon 8 Gen 2, 5500 mAh battery, 100W SUPERVOOC, 1.5K LTPO ProXDR Display.",
    price: "₹45,999",
    originalPrice: "₹47,999",
    discount: "4%",
    category: "Electronics",
    rating: 4.5,
    reviews: 14000,
    image: "https://m.media-amazon.com/images/I/717Qo4MH97L._AC_SL1500_.jpg",
    asin: "B0CQPGM4XJ",
    badge: "Trending",
    bankOffer: "₹2,000 Instant Discount on ICICI"
  },
  {
    id: 47,
    title: "Puma Unisex-Adult Smash V2 L Sneakers",
    description: "Classic leather sneakers for everyday wear. Comfortable and durable.",
    price: "₹1,749",
    originalPrice: "₹3,499",
    discount: "50%",
    category: "Fashion",
    rating: 4.3,
    reviews: 65000,
    image: "https://m.media-amazon.com/images/I/61I13mE1pHL._AC_SL1500_.jpg",
    asin: "B079Z1K9ZS",
    badge: "Best Seller"
  },
  {
    id: 48,
    title: "Cetaphil Gentle Skin Cleanser 500ml",
    description: "Hydrating face wash for dry to normal sensitive skin. Dermatologist recommended.",
    price: "₹915",
    originalPrice: "₹1,099",
    discount: "17%",
    category: "Health & Beauty",
    rating: 4.6,
    reviews: 42000,
    image: "https://m.media-amazon.com/images/I/51wV+Q7O7-L._AC_SL1000_.jpg",
    asin: "B002K6E822",
    badge: "Amazon Pick"
  },
  {
    id: 49,
    title: "Samsung 24-inch Odyssey G3 Gaming Monitor",
    description: "144Hz refresh rate, 1ms response time, AMD FreeSync Premium, Height Adjustable Stand.",
    price: "₹11,499",
    originalPrice: "₹24,000",
    discount: "52%",
    category: "Gaming",
    rating: 4.4,
    reviews: 8900,
    image: "https://m.media-amazon.com/images/I/81S8A95ZlLL._AC_SL1500_.jpg",
    asin: "B09MT5TDFL",
    badge: "Deal of the Day",
    dealScore: 94
  },
  {
    id: 50,
    title: "Echo Show 8 (2nd Gen)",
    description: "Smart display with Alexa and 13MP camera. Make video calls, watch Prime Video, and control smart home.",
    price: "₹7,499",
    originalPrice: "₹13,999",
    discount: "46%",
    category: "Smart Home",
    rating: 4.5,
    reviews: 21000,
    image: "https://m.media-amazon.com/images/I/61-pE8A2AFL._AC_SL1000_.jpg",
    asin: "B084TNMMMD",
    badge: "Bundle Deal",
    dealEnds: "2026-04-28T23:59:59"
  },
  // ---- APPLIANCES ----
  { id:51, title:"Bajaj Majesty 1200W Dry Iron", description:"Lightweight dry iron with non-stick coating and adjustable temperature.", price:"₹399", originalPrice:"₹799", discount:"50%", category:"Appliances", rating:4.2, reviews:18500, image:"https://m.media-amazon.com/images/I/51gBYOfUxzL._AC_SL1500_.jpg", asin:"B07FNSM5YF", badge:"Best Seller" },
  { id:52, title:"Philips HL7756 Mixer Grinder 750W", description:"3 stainless steel jars with turbo motor for effortless grinding.", price:"₹2,799", originalPrice:"₹4,495", discount:"38%", category:"Appliances", rating:4.3, reviews:42000, image:"https://m.media-amazon.com/images/I/51OweRNO0jL._AC_SL1500_.jpg", asin:"B07WLS5TFG", badge:"Top Rated" },
  { id:53, title:"Havells Instanio Prime 3L Instant Water Heater", description:"3-litre instant geyser with whirlflow technology and ISI mark.", price:"₹2,999", originalPrice:"₹5,090", discount:"41%", category:"Appliances", rating:4.4, reviews:15000, image:"https://m.media-amazon.com/images/I/51jDmQqLEDL._AC_SL1500_.jpg", asin:"B09HKYX1Z5", badge:"Lightning Deal" },
  { id:54, title:"Prestige IRIS 750W Mixer Grinder", description:"3 jars mixer grinder with 750W motor and stainless steel blades.", price:"₹2,499", originalPrice:"₹4,245", discount:"41%", category:"Appliances", rating:4.1, reviews:12000, image:"https://m.media-amazon.com/images/I/61Gfti7OPuL._AC_SL1500_.jpg", asin:"B07VZ4SQN5", badge:"Deal of the Day" },
  { id:55, title:"Crompton Amica 15L Storage Water Heater", description:"15-litre storage geyser with advanced 3-level safety.", price:"₹4,499", originalPrice:"₹8,500", discount:"47%", category:"Appliances", rating:4.3, reviews:9800, image:"https://m.media-amazon.com/images/I/41sFgJYBBuL._AC_SL1500_.jpg", asin:"B0BQH3MHSG", badge:"Best Value" },
  { id:56, title:"Butterfly Smart Glass 3 Burner Gas Stove", description:"Toughened glass top gas stove with brass burners.", price:"₹2,199", originalPrice:"₹4,590", discount:"52%", category:"Appliances", rating:4.2, reviews:22000, image:"https://m.media-amazon.com/images/I/71TF+XNQHQL._AC_SL1500_.jpg", asin:"B07M8HKPN4", badge:"Lightning Deal", dealEnds:"2026-04-29T23:59:59" },
  { id:57, title:"Wonderchef Nutri-Blend 400W Mixer", description:"Compact personal blender with 2 jars for smoothies and shakes.", price:"₹1,499", originalPrice:"₹2,499", discount:"40%", category:"Appliances", rating:4.0, reviews:31000, image:"https://m.media-amazon.com/images/I/61MSJwC2R3L._AC_SL1500_.jpg", asin:"B07BHYXWW1", badge:"Popular" },
  // ---- AUTOMOTIVE ----
  { id:58, title:"Bergmann Typhoon Car Vacuum Cleaner", description:"Portable 12V car vacuum with high suction power and HEPA filter.", price:"₹1,299", originalPrice:"₹2,499", discount:"48%", category:"Automotive", rating:4.1, reviews:8500, image:"https://m.media-amazon.com/images/I/61mAxjpb5ML._AC_SL1500_.jpg", asin:"B07JR2TBGY", badge:"Best Seller" },
  { id:59, title:"Bosch F002H23105 Wiper Blade Set", description:"Premium wiper blades for clear visibility in all weather conditions.", price:"₹499", originalPrice:"₹899", discount:"44%", category:"Automotive", rating:4.3, reviews:6200, image:"https://m.media-amazon.com/images/I/61vPFhJ-7LL._AC_SL1500_.jpg", asin:"B00ISNKP4C", badge:"Top Pick" },
  { id:60, title:"Jopasu Car Duster", description:"Microfiber car duster for scratch-free cleaning of car exteriors.", price:"₹349", originalPrice:"₹699", discount:"50%", category:"Automotive", rating:4.2, reviews:14000, image:"https://m.media-amazon.com/images/I/71YaW-0GALL._AC_SL1500_.jpg", asin:"B00NMWWWH0", badge:"Best Value" },
  { id:61, title:"CARZEX 7D Leather Car Seat Covers", description:"Premium 7D leather seat covers with memory foam for all car models.", price:"₹3,999", originalPrice:"₹7,999", discount:"50%", category:"Automotive", rating:4.0, reviews:4500, image:"https://m.media-amazon.com/images/I/71IRGD1sALL._AC_SL1500_.jpg", asin:"B0BG3JFHTZ", badge:"Premium" },
  { id:62, title:"Amkette Trubeats Igloo Car Charger QC 3.0", description:"Dual USB quick charge 3.0 car charger with LED voltage display.", price:"₹599", originalPrice:"₹1,199", discount:"50%", category:"Automotive", rating:4.4, reviews:7800, image:"https://m.media-amazon.com/images/I/61A0rQ9tP6L._AC_SL1500_.jpg", asin:"B07PZCD3Y4", badge:"Fast Seller" },
  // ---- BABY & KIDS ----
  { id:63, title:"LuvLap Comfy Baby Walker", description:"Adjustable height baby walker with musical toy tray and stopper.", price:"₹1,699", originalPrice:"₹3,499", discount:"51%", category:"Baby & Kids", rating:4.2, reviews:11000, image:"https://m.media-amazon.com/images/I/71hy7BQZWBL._AC_SL1500_.jpg", asin:"B07BHLXJ95", badge:"Best Seller" },
  { id:64, title:"Pampers All-Round Protection Diapers (Pack of 78)", description:"Double leak guards and up to 12 hours absorption for babies.", price:"₹799", originalPrice:"₹1,299", discount:"38%", category:"Baby & Kids", rating:4.5, reviews:65000, image:"https://m.media-amazon.com/images/I/71nE-7IqyjL._AC_SL1500_.jpg", asin:"B07GZFBW3N", badge:"Amazon's Choice" },
  { id:65, title:"Fisher-Price Laugh & Learn Smart Stages Chair", description:"Interactive learning chair with 50+ songs, tunes and phrases.", price:"₹2,999", originalPrice:"₹5,499", discount:"45%", category:"Baby & Kids", rating:4.6, reviews:8200, image:"https://m.media-amazon.com/images/I/81C6FgPjqjL._AC_SL1500_.jpg", asin:"B07MWCLMPS", badge:"Top Rated" },
  { id:66, title:"Himalaya Gentle Baby Shampoo 400ml", description:"Tear-free gentle baby shampoo with hibiscus and chickpea.", price:"₹199", originalPrice:"₹320", discount:"38%", category:"Baby & Kids", rating:4.4, reviews:35000, image:"https://m.media-amazon.com/images/I/51cpg-UDBTL._AC_SL1200_.jpg", asin:"B00ECCZIQO", badge:"Best Value" },
  { id:67, title:"MeeMee Baby Carrier 6-in-1", description:"Lightweight 6-position baby carrier for 0-2 year olds.", price:"₹899", originalPrice:"₹1,799", discount:"50%", category:"Baby & Kids", rating:4.1, reviews:6700, image:"https://m.media-amazon.com/images/I/71g7VQd7P6L._AC_SL1500_.jpg", asin:"B07P5T1MZ1", badge:"Lightning Deal", dealEnds:"2026-04-30T23:59:59" },
  // ---- MUSICAL INSTRUMENTS ----
  { id:68, title:"Kadence Acoustica Series Acoustic Guitar", description:"Full-size dreadnought acoustic guitar with truss rod. Ideal for beginners.", price:"₹3,290", originalPrice:"₹6,999", discount:"53%", category:"Musical Instruments", rating:4.2, reviews:9400, image:"https://m.media-amazon.com/images/I/71kkPFoMCrL._AC_SL1500_.jpg", asin:"B01BPM4QFO", badge:"Best Seller" },
  { id:69, title:"Casio SA-76 Mini Keyboard 44 Keys", description:"Compact 44-key mini keyboard with 100 tones and 50 rhythms.", price:"₹3,395", originalPrice:"₹5,495", discount:"38%", category:"Musical Instruments", rating:4.5, reviews:7200, image:"https://m.media-amazon.com/images/I/71PQcMRMjmL._AC_SL1500_.jpg", asin:"B00BEM0AYU", badge:"Top Rated" },
  { id:70, title:"Vault UK-21 Soprano Ukulele Mahogany", description:"21-inch soprano ukulele with mahogany body and aquila strings.", price:"₹1,599", originalPrice:"₹2,999", discount:"47%", category:"Musical Instruments", rating:4.3, reviews:5100, image:"https://m.media-amazon.com/images/I/61kXU+PE3YL._AC_SL1200_.jpg", asin:"B0756H2SH3", badge:"Popular" },
  { id:71, title:"Juarez JRZ38C Acoustic Guitar Kit", description:"38-inch cutaway acoustic guitar with bag, strings, picks and strap.", price:"₹2,290", originalPrice:"₹4,999", discount:"54%", category:"Musical Instruments", rating:4.1, reviews:14500, image:"https://m.media-amazon.com/images/I/61CwMQ3fK2L._AC_SL1200_.jpg", asin:"B07NQ23Z6T", badge:"Bundle Deal" },
  { id:72, title:"Havana AAG39 Acoustic Guitar Natural", description:"Full-size 39-inch classical guitar with nylon strings.", price:"₹1,999", originalPrice:"₹3,999", discount:"50%", category:"Musical Instruments", rating:4.0, reviews:3200, image:"https://m.media-amazon.com/images/I/71v50yFKFPL._AC_SL1500_.jpg", asin:"B07ND8RTTM", badge:"Deal of the Day" },
  // ---- MORE ELECTRONICS ----
  { id:73, title:"Samsung 980 500GB NVMe SSD", description:"PCIe 3.0 NVMe M.2 SSD with up to 3,100 MB/s read speeds.", price:"₹3,199", originalPrice:"₹5,999", discount:"47%", category:"Electronics", rating:4.7, reviews:28000, image:"https://m.media-amazon.com/images/I/71AgJtBbhpL._AC_SL1500_.jpg", asin:"B08V7GT6F3", badge:"Best Seller", dealScore:92 },
  { id:74, title:"Logitech MK270r Wireless Keyboard Mouse Combo", description:"Full-size wireless keyboard and mouse combo with 2.4GHz nano receiver.", price:"₹1,395", originalPrice:"₹2,295", discount:"39%", category:"Electronics", rating:4.3, reviews:41000, image:"https://m.media-amazon.com/images/I/51+BV7wYRnL._AC_SL1500_.jpg", asin:"B08BKTN6CV", badge:"Amazon's Choice" },
  { id:75, title:"Redgear Shadow Amulet Wired Gaming Mouse", description:"RGB gaming mouse with 4800 DPI optical sensor and 7 buttons.", price:"₹499", originalPrice:"₹999", discount:"50%", category:"Gaming", rating:4.1, reviews:15000, image:"https://m.media-amazon.com/images/I/51oI9Ee14bL._AC_SL1500_.jpg", asin:"B098P6B22T", badge:"Hot Deal" },
  { id:76, title:"Portronics SoundDrum 1 10W Bluetooth Speaker", description:"Portable wireless speaker with TWS, USB, FM and AUX connectivity.", price:"₹899", originalPrice:"₹1,899", discount:"53%", category:"Electronics", rating:4.2, reviews:19000, image:"https://m.media-amazon.com/images/I/51E8Ry5COVL._AC_SL1500_.jpg", asin:"B09N3T7GQV", badge:"Top Pick" },
  { id:77, title:"Ambrane 20000mAh Power Bank", description:"20000mAh Li-Polymer power bank with 20W fast charging and dual output.", price:"₹1,099", originalPrice:"₹2,499", discount:"56%", category:"Electronics", rating:4.3, reviews:32000, image:"https://m.media-amazon.com/images/I/61v25gmKQdL._AC_SL1500_.jpg", asin:"B09NNPP9SB", badge:"Lightning Deal", dealEnds:"2026-04-29T15:59:59" },
  // ---- MORE FASHION ----
  { id:78, title:"Levi's Men's 511 Slim Fit Jeans", description:"Classic slim fit jeans with stretch denim for all-day comfort.", price:"₹1,499", originalPrice:"₹3,499", discount:"57%", category:"Fashion", rating:4.4, reviews:18000, image:"https://m.media-amazon.com/images/I/71hCKZ60vsL._AC_SL1500_.jpg", asin:"B07JR8TDZK", badge:"Best Seller" },
  { id:79, title:"US Polo Assn. Men's Polo T-Shirt", description:"Classic cotton polo with signature logo embroidery.", price:"₹699", originalPrice:"₹1,599", discount:"56%", category:"Fashion", rating:4.3, reviews:24000, image:"https://m.media-amazon.com/images/I/61oAbWDkHrL._AC_SL1500_.jpg", asin:"B08KGC8QRH", badge:"Top Rated" },
  { id:80, title:"Fastrack Analog Men's Watch", description:"Stylish analog watch with leather strap and water-resistant casing.", price:"₹799", originalPrice:"₹1,595", discount:"50%", category:"Fashion", rating:4.2, reviews:35000, image:"https://m.media-amazon.com/images/I/81B1PqyINcL._AC_SL1500_.jpg", asin:"B00IDFNJHY", badge:"Popular" },
  { id:81, title:"Lavie Women's Handbag", description:"Premium faux leather handbag with multiple compartments.", price:"₹899", originalPrice:"₹2,300", discount:"61%", category:"Fashion", rating:4.1, reviews:12000, image:"https://m.media-amazon.com/images/I/81GJI3WE0WL._AC_SL1500_.jpg", asin:"B0B7FFQNXR", badge:"Deal of the Day" },
  // ---- MORE HOME & KITCHEN ----
  { id:82, title:"Pigeon by Stovekraft 12-Piece Non-Stick Cookware Set", description:"Complete non-stick cookware set with kadai, tawa, fry pan and more.", price:"₹1,099", originalPrice:"₹2,495", discount:"56%", category:"Home & Kitchen", rating:4.1, reviews:38000, image:"https://m.media-amazon.com/images/I/71T5EF8m-4L._AC_SL1500_.jpg", asin:"B07BQJV6K5", badge:"Best Seller" },
  { id:83, title:"Prestige PKOSS Electric Kettle 1.5L", description:"1500W stainless steel electric kettle with auto shut-off.", price:"₹549", originalPrice:"₹1,095", discount:"50%", category:"Home & Kitchen", rating:4.2, reviews:52000, image:"https://m.media-amazon.com/images/I/61oADOqpDML._AC_SL1500_.jpg", asin:"B00HNKR0V0", badge:"Amazon's Choice" },
  { id:84, title:"Solimo 100% Cotton Bath Towel Set of 2", description:"Quick-dry 500 GSM bath towels, ultra soft and durable.", price:"₹499", originalPrice:"₹999", discount:"50%", category:"Home & Kitchen", rating:4.3, reviews:27000, image:"https://m.media-amazon.com/images/I/81xotUMFdUL._AC_SL1500_.jpg", asin:"B07WGMHV5Y", badge:"Best Value" },
  { id:85, title:"Milton Thermosteel Flip Lid Flask 1L", description:"24-hour hot and cold vacuum insulated stainless steel flask.", price:"₹649", originalPrice:"₹1,375", discount:"53%", category:"Home & Kitchen", rating:4.4, reviews:46000, image:"https://m.media-amazon.com/images/I/41y8diilxzL._AC_SL1000_.jpg", asin:"B071JMDHBP", badge:"Top Pick" },
  // ---- MORE HEALTH & BEAUTY ----
  { id:86, title:"Beardo Activated Charcoal Face Wash 100ml", description:"Deep cleansing charcoal face wash that removes dirt, oil and toxins.", price:"₹199", originalPrice:"₹450", discount:"56%", category:"Health & Beauty", rating:4.1, reviews:22000, image:"https://m.media-amazon.com/images/I/51cNrpGSwKL._AC_SL1100_.jpg", asin:"B07B7JK1MC", badge:"Best Seller" },
  { id:87, title:"Philips BT1233 Beard Trimmer", description:"Skin-friendly cordless trimmer with USB charging and 20 length settings.", price:"₹899", originalPrice:"₹1,495", discount:"40%", category:"Health & Beauty", rating:4.3, reviews:48000, image:"https://m.media-amazon.com/images/I/51Q4bBGLSoL._AC_SL1500_.jpg", asin:"B0B4D6HKJY", badge:"Amazon's Choice" },
  { id:88, title:"Himalaya Purifying Neem Face Wash 200ml", description:"Purifying neem and turmeric face wash for clear, blemish-free skin. Dermatologist recommended.", price:"₹149", originalPrice:"₹250", discount:"40%", category:"Health & Beauty", rating:4.4, reviews:85000, image:"https://m.media-amazon.com/images/I/51cNrpGSwKL._AC_SL1100_.jpg", asin:"B00C7YDKW6", badge:"Amazon's Choice" },
  { id:89, title:"WOW Skin Science Apple Cider Vinegar Shampoo 300ml", description:"Paraben and sulphate free shampoo with apple cider vinegar.", price:"₹349", originalPrice:"₹599", discount:"42%", category:"Health & Beauty", rating:4.2, reviews:56000, image:"https://m.media-amazon.com/images/I/61+8RUHM7ML._AC_SL1500_.jpg", asin:"B07BDZYGYR", badge:"Popular" },
  // ---- MORE SPORTS & FITNESS ----
  { id:90, title:"Boldfit Yoga Mat 6mm Anti-Slip", description:"Extra thick NBR yoga mat with carrying strap, anti-tear surface.", price:"₹399", originalPrice:"₹999", discount:"60%", category:"Sports & Fitness", rating:4.2, reviews:28000, image:"https://m.media-amazon.com/images/I/71-3jAFbR-L._AC_SL1500_.jpg", asin:"B08VWRT1D3", badge:"Best Seller" },
  { id:91, title:"Nivia Storm Football Size 5", description:"Machine stitched PVC football for training and recreational play.", price:"₹349", originalPrice:"₹699", discount:"50%", category:"Sports & Fitness", rating:4.1, reviews:15000, image:"https://m.media-amazon.com/images/I/71E5pB8q1iL._AC_SL1500_.jpg", asin:"B00LZPKDSE", badge:"Top Pick" },
  { id:92, title:"Strauss Adjustable Dumbbell Set 20kg", description:"PVC dumbbell set with adjustable weight plates and non-slip grip.", price:"₹1,299", originalPrice:"₹2,999", discount:"57%", category:"Sports & Fitness", rating:4.0, reviews:9500, image:"https://m.media-amazon.com/images/I/61eH-vRQDXL._AC_SL1500_.jpg", asin:"B07KF89P7T", badge:"Deal of the Day" },
  { id:93, title:"COSCO Cricket Bat Kashmir Willow", description:"Full-size Kashmir willow cricket bat with cane handle.", price:"₹599", originalPrice:"₹1,250", discount:"52%", category:"Sports & Fitness", rating:4.2, reviews:7800, image:"https://m.media-amazon.com/images/I/41sHcQk5ZFL._AC_SL1500_.jpg", asin:"B00LWXQLXA", badge:"Lightning Deal" },
  // ---- MORE BOOKS ----
  { id:94, title:"Deep Work – Cal Newport", description:"Rules for focused success in a distracted world. A guide to thriving in the knowledge economy.", price:"₹349", originalPrice:"₹699", discount:"50%", category:"Books", rating:4.6, reviews:18000, image:"https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_SY466_.jpg", asin:"B00X47ZVXM", badge:"Top Rated", dealScore:88 },
  { id:95, title:"Think and Grow Rich – Napoleon Hill", description:"The original self-help classic that has sold over 100 million copies worldwide.", price:"₹149", originalPrice:"₹350", discount:"57%", category:"Books", rating:4.6, reviews:72000, image:"https://m.media-amazon.com/images/I/61y7G8Ly0iL._AC_SY466_.jpg", asin:"B09LC8V4PX", badge:"All-Time Classic" },
  { id:96, title:"Shoe Dog – Phil Knight (Nike Memoir)", description:"A memoir by the creator of Nike. One of the most compelling, candid business books ever written.", price:"₹299", originalPrice:"₹599", discount:"50%", category:"Books", rating:4.7, reviews:28000, image:"https://m.media-amazon.com/images/I/81MtOUxkQ3L._AC_SY466_.jpg", asin:"B0BKFV7WY5", badge:"Editor's Pick" },
  { id:97, title:"Ikigai: The Japanese Secret to a Long Life", description:"Discover the Japanese philosophy for a purposeful and happy life.", price:"₹199", originalPrice:"₹350", discount:"43%", category:"Books", rating:4.5, reviews:55000, image:"https://m.media-amazon.com/images/I/81l3rZK4lnL._AC_SL1500_.jpg", asin:"B06XWCBQ45", badge:"Popular" },
  // ---- MORE SMART HOME ----
  { id:98, title:"Philips SmartSleep Wake-Up Light HF3510", description:"Sunrise simulation wake-up light with FM radio, 5 natural sounds and 10 brightness settings.", price:"₹5,499", originalPrice:"₹8,995", discount:"39%", category:"Smart Home", rating:4.3, reviews:4200, image:"https://m.media-amazon.com/images/I/71xoR4A6q3L._AC_SL1500_.jpg", asin:"B0CP9R51GS", badge:"New Arrival" },
  { id:99, title:"Realme Smart Cam 360° 1080p WiFi Camera", description:"360° pan tilt, 1080p FHD, night vision, two-way talk, motion detection, works with Alexa.", price:"₹1,299", originalPrice:"₹2,499", discount:"48%", category:"Smart Home", rating:4.2, reviews:15000, image:"https://m.media-amazon.com/images/I/41xLVPkdlbL._AC_SL1000_.jpg", asin:"B0B1LQYWM3", badge:"Hot Deal" },
  { id:100, title:"Wipro 9W Smart LED Bulb (WiFi)", description:"16 million color options controllable via Alexa, Google Home or app.", price:"₹399", originalPrice:"₹799", discount:"50%", category:"Smart Home", rating:4.1, reviews:22000, image:"https://m.media-amazon.com/images/I/51xYbEU22UL._AC_SL1500_.jpg", asin:"B07TKHY4TL", badge:"Best Value" },
  // ---- MORE GAMING ----
  { id:101, title:"Cosmic Byte CB-GK-16 Mechanical Keyboard", description:"Full RGB mechanical gaming keyboard with Outemu Blue switches.", price:"₹1,899", originalPrice:"₹3,999", discount:"53%", category:"Gaming", rating:4.2, reviews:16000, image:"https://m.media-amazon.com/images/I/61Vf8GTbO2L._AC_SL1500_.jpg", asin:"B07JZY7Z9K", badge:"Best Seller" },
  { id:102, title:"Ant Esports H1000 Pro Gaming Headset", description:"Surround sound gaming headset with noise-cancelling mic.", price:"₹799", originalPrice:"₹1,599", discount:"50%", category:"Gaming", rating:4.1, reviews:21000, image:"https://m.media-amazon.com/images/I/61CGkHGUYhL._AC_SL1500_.jpg", asin:"B0BYNMK1Y2", badge:"Popular" },
  { id:103, title:"EvoFox Elite Ops Wireless Gamepad", description:"Wireless controller for PC and PS3 with dual vibration and turbo.", price:"₹1,299", originalPrice:"₹2,499", discount:"48%", category:"Gaming", rating:4.0, reviews:8900, image:"https://m.media-amazon.com/images/I/61kq1LiV4UL._AC_SL1500_.jpg", asin:"B09Y57GDGV", badge:"Hot Deal" },
  // ---- MORE TOYS & GAMES ----
  { id:104, title:"LEGO Classic Creative Bricks 10692", description:"221 pieces classic LEGO set for endless creative building fun.", price:"₹999", originalPrice:"₹1,499", discount:"33%", category:"Toys & Games", rating:4.7, reviews:12000, image:"https://m.media-amazon.com/images/I/81dkJKKBPhL._AC_SL1500_.jpg", asin:"B00NHQFA1I", badge:"Top Rated" },
  { id:105, title:"Funskool Games Monopoly", description:"The classic family board game of property trading and strategy.", price:"₹399", originalPrice:"₹699", discount:"43%", category:"Toys & Games", rating:4.5, reviews:19000, image:"https://m.media-amazon.com/images/I/91bsfnYfb6L._AC_SL1500_.jpg", asin:"B0769G4JRZ", badge:"Best Seller" },
  { id:106, title:"Toyshine Remote Control Car 1:18 Scale", description:"High speed RC car with rechargeable battery and 2.4GHz remote.", price:"₹799", originalPrice:"₹1,799", discount:"56%", category:"Toys & Games", rating:4.0, reviews:6500, image:"https://m.media-amazon.com/images/I/71hVVAhWqrL._AC_SL1500_.jpg", asin:"B0BFM22Y9Z", badge:"Lightning Deal", dealEnds:"2026-04-30T20:00:00" },
  // ---- MORE OFFICE ----
  { id:107, title:"Cello Butterfinger Ball Pen Set of 10", description:"Lightweight ergonomic ball pens with smooth writing experience.", price:"₹60", originalPrice:"₹120", discount:"50%", category:"Office & Stationery", rating:4.2, reviews:45000, image:"https://m.media-amazon.com/images/I/71Xw5KPb9HL._AC_SL1500_.jpg", asin:"B015O1EQMG", badge:"Best Value" },
  { id:108, title:"Classmate Pulse Notebook Pack of 6", description:"6-pack spiral notebooks, 200 pages each with single line ruling.", price:"₹299", originalPrice:"₹540", discount:"45%", category:"Office & Stationery", rating:4.4, reviews:28000, image:"https://m.media-amazon.com/images/I/71YoKAr9kGL._AC_SL1500_.jpg", asin:"B07H6YVQPN", badge:"Popular" },
  { id:109, title:"HP 63 Black Ink Cartridge", description:"Original HP ink cartridge for DeskJet, OfficeJet and ENVY printers.", price:"₹799", originalPrice:"₹1,299", discount:"38%", category:"Office & Stationery", rating:4.3, reviews:15000, image:"https://m.media-amazon.com/images/I/61Ahr6LbFOL._AC_SL1500_.jpg", asin:"B00XTFFLGE", badge:"Amazon's Choice" },
  // ---- PREMIUM ELECTRONICS ----
  { id:110, title:"Apple AirPods 3rd Generation", description:"Spatial audio with dynamic head tracking, adaptive EQ and MagSafe case.", price:"₹14,900", originalPrice:"₹19,900", discount:"25%", category:"Electronics", rating:4.6, reviews:42000, image:"https://m.media-amazon.com/images/I/71zny7BTRlL._AC_SL1500_.jpg", asin:"B09JQL3NWT", badge:"Premium", dealScore:90 },
  { id:111, title:"Samsung Galaxy Buds FE", description:"Active noise cancellation, 30-hour battery with case, IPX2 rated.", price:"₹4,999", originalPrice:"₹6,999", discount:"29%", category:"Electronics", rating:4.4, reviews:18000, image:"https://m.media-amazon.com/images/I/51QeY+3GRkL._AC_SL1500_.jpg", asin:"B0CHXJNZ72", badge:"Top Rated" },
  { id:112, title:"OnePlus Nord Buds 2r", description:"12.4mm titanium drivers, up to 38 hours playback, IP55 rated.", price:"₹1,799", originalPrice:"₹2,999", discount:"40%", category:"Electronics", rating:4.3, reviews:25000, image:"https://m.media-amazon.com/images/I/51atM3P3YxL._AC_SL1500_.jpg", asin:"B0CL5F56W2", badge:"Best Value" },
  { id:113, title:"Lenovo IdeaPad Slim 3 Laptop 15.6\"", description:"AMD Ryzen 5, 8GB RAM, 512GB SSD, 15.6\" FHD IPS display.", price:"₹34,990", originalPrice:"₹56,690", discount:"38%", category:"Electronics", rating:4.3, reviews:8500, image:"https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg", asin:"B0CGGDNYZQ", badge:"Best Seller", dealScore:85 },
  { id:114, title:"Fire TV Stick 4K Max", description:"4K streaming with Wi-Fi 6E and Alexa Voice Remote.", price:"₹4,299", originalPrice:"₹6,999", discount:"39%", category:"Smart Home", rating:4.5, reviews:55000, image:"https://m.media-amazon.com/images/I/61aFt4MjICL._AC_SL1000_.jpg", asin:"B0BTFK25BZ", badge:"Amazon's Choice", dealScore:87 },
  // ---- MORE DIVERSE PRODUCTS ----
  { id:115, title:"Noise ColorFit Pro 4 Smartwatch", description:"1.72\" AMOLED display, Bluetooth calling, 100+ sports modes.", price:"₹2,499", originalPrice:"₹5,999", discount:"58%", category:"Electronics", rating:4.2, reviews:32000, image:"https://m.media-amazon.com/images/I/61LlUJCBvnL._AC_SL1500_.jpg", asin:"B0B4NCRF79", badge:"Lightning Deal", dealEnds:"2026-04-29T18:00:00" },
  { id:116, title:"Syska LED 9W Bulb Pack of 10", description:"B22 base, 810 lumens, energy-efficient LED bulbs with 2-year warranty.", price:"₹399", originalPrice:"₹800", discount:"50%", category:"Home & Kitchen", rating:4.3, reviews:42000, image:"https://m.media-amazon.com/images/I/41AQE3zPKOL._AC_SL1000_.jpg", asin:"B071XD8T12", badge:"Best Value" },
  { id:117, title:"Skybags Brat 46 Ltrs Laptop Backpack", description:"46-litre daypack with padded laptop compartment and rain cover.", price:"₹799", originalPrice:"₹2,050", discount:"61%", category:"Fashion", rating:4.2, reviews:28000, image:"https://m.media-amazon.com/images/I/81bh4QHqwPL._AC_SL1500_.jpg", asin:"B0777Q4KDP", badge:"Deal of the Day" },
  { id:118, title:"Boat Rockerz 255 Pro+ Wireless Neckband", description:"40 hours playback, ASAP charge, dual pairing, IPX5 water resistant.", price:"₹799", originalPrice:"₹2,990", discount:"73%", category:"Electronics", rating:4.1, reviews:95000, image:"https://m.media-amazon.com/images/I/51dTUCIvruL._AC_SL1500_.jpg", asin:"B09N3Z2BV3", badge:"#1 Best Seller", dealScore:93 },
  { id:119, title:"Cadbury Celebrations Premium Assorted Pack 286g", description:"Premium gift box with assorted chocolates for all occasions.", price:"₹249", originalPrice:"₹400", discount:"38%", category:"Home & Kitchen", rating:4.4, reviews:18000, image:"https://m.media-amazon.com/images/I/71xmUz0UEYL._AC_SL1500_.jpg", asin:"B00VG4X5US", badge:"Gift Pick" },
  { id:120, title:"JBL Go 3 Portable Bluetooth Speaker", description:"Ultra-portable waterproof speaker with JBL Pro Sound and IP67 rating.", price:"₹2,699", originalPrice:"₹3,999", discount:"33%", category:"Electronics", rating:4.5, reviews:38000, image:"https://m.media-amazon.com/images/I/71f5MXHPGVL._AC_SL1500_.jpg", asin:"B08KZPF7M2", badge:"Top Rated", dealScore:86 },
  // ---- ADDITIONAL PRODUCTS FOR 125+ ----
  { id:121, title:"Mivi Roam 2 Bluetooth Speaker", description:"5W portable speaker with 24-hour playtime, waterproof and built-in mic.", price:"₹899", originalPrice:"₹2,499", discount:"64%", category:"Electronics", rating:4.2, reviews:15000, image:"https://m.media-amazon.com/images/I/51hJ0b1Qf3L._AC_SL1500_.jpg", asin:"B08CFQKZMT", badge:"Best Value" },
  { id:122, title:"Vega Crux Open Face Helmet", description:"ISI certified motorbike helmet with scratch-resistant visor.", price:"₹699", originalPrice:"₹1,299", discount:"46%", category:"Automotive", rating:4.3, reviews:42000, image:"https://m.media-amazon.com/images/I/71T0y7f5yPL._AC_SL1500_.jpg", asin:"B01MTCP5K8", badge:"Best Seller" },
  { id:123, title:"Philips HD6975/00 Digital Air Fryer", description:"4.1L digital air fryer with 7 presets and keep warm function.", price:"₹5,999", originalPrice:"₹11,995", discount:"50%", category:"Home & Kitchen", rating:4.4, reviews:22000, image:"https://m.media-amazon.com/images/I/71S7hLrN8gL._AC_SL1500_.jpg", asin:"B08LKQ7N9R", badge:"Top Rated" },
  { id:124, title:"Gillette Mach 3 Shaving Razor", description:"3-blade razor with lubricating strip and premium handle.", price:"₹299", originalPrice:"₹599", discount:"50%", category:"Health & Beauty", rating:4.5, reviews:65000, image:"https://m.media-amazon.com/images/I/51Yc3+P+uWL._AC_SL1500_.jpg", asin:"B0038LPP9E", badge:"Amazon's Choice" },
  { id:125, title:"Amazon Basics AA Batteries Pack of 20", description:"High-performance alkaline batteries with 10-year shelf life.", price:"₹249", originalPrice:"₹499", discount:"50%", category:"Home & Kitchen", rating:4.3, reviews:58000, image:"https://m.media-amazon.com/images/I/71ZN9F+2nJL._AC_SL1500_.jpg", asin:"B00MNV8E0C", badge:"Best Value" }
];

// Expose to window for scripts that reference window.PRODUCTS / window.CATEGORIES
if (typeof window !== 'undefined') {
  window.PRODUCTS = PRODUCTS;
  window.CATEGORIES = CATEGORIES;
  window.SITE_CONFIG = SITE_CONFIG;
}
